---
kind: pipeline
type: kubernetes
name: default
platform:
  os: linux

trigger:
  branch:
    - prod
  event:
    - tag

steps:
  - name: publish
    image: plugins/docker
    dockerfile: Dockerfile
    context: .
    settings:
      repo: nemo:5001/services/screenshot-service
      registry: nemo:5001
      insecure: true
      auto_tag: true

image_pull_secrets:
  - nemo-registry-login